function sys = mylinearize(io,op)
% MYLINEARIZE Linearize the Simulink model - TAU_Khomutov_7_model.
%
% SYS = MYLINEARIZE(IO,OP) linearizes the Simulink model TAU_Khomutov_7_model
% using the analysis I/Os IO about the operating point OP.

% MATLAB(R) file generated by MATLAB(R) 8.3 and Simulink Control Design (TM) 4.0.
%
% Generated on: 06-Apr-2018 20:21:11

%% Specify the model name
model = 'TAU_Khomutov_7_model';

%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)

